## 2025년 6월 14일

---


# 복습


## 콜백

- 자바스크립트 호스트 환경이 제공하는 여러 함수를 사용하면 비동기(asynchronous) 동작을 스케줄링 할 수 있다. 원하는 때 동작이 시작할 수 있다.
- setTimeout은 스케줄링에 사용되는 가장 대표적인 함수이다.
- 실무에서 맞닥뜨리는 비동기 동작은 아주 다양하다. 스크립트나 모듈을 로딩하는 것 또한 비동기 동작이다.
- src에 있는 스크립트를 읽어오는 함수 loadScript(src)를 예시로 비동기 동작 처리가 어떻게 일어나는지 알아보자.

```js
function loadScripty(src) {
// <script> 태그를 만들고 페이지에 태그를 추가한다.
// 태그가 페이지에 추가되면 src에 있는 스크립트를 로딩하고 실행한다.
let script = document.createElement('script');
script.src = src;
document.head.append(script);
}
```

- 함수 loadScript(src) 는 <scripty src="...">를 동적으로 만들고 이를 문서에 추가한다. 브라우저는 자동으로 태그에 있는 스크립트르 불러오고 로딩이 완료되면 스크립트를 실행한다.
- loadscript(src) 사용법은 다음과 같다.
```js
// 해당 경로에 위치한 스크립트를 불러오고 실행함
loadScript('/my/scirpt.js');
```
- 그런데 이 스크립트는 '비동기적으로'실행된다. 로딩은 지금 당장 시작되더라도 실행은 함수가 끝난 후에야 되기 때문이다.
- 따라서 laodscript(...) 아래에 있는 코드들은 스크립트 로딩이 종료되는 걸 기다리지 않는다.
```js
loadscript('/my/script.js'); // script.js엔 "function newFunction() {...}"이 있다.
newFunction(); // 함수가 존재하지 않는다는 에러가 발생한다.
```
- 에러는 브라우저가 스크립트를 읽어올 수 있는 시간을 충분히 확보하지 못했기 때문에 발생한다. 그런데 현재로서는 함수 loadSccript에서 스크립트 로딩이 완료되었는지 알 방법이 ㅇ벗다.
- 언젠간 스크립트가 로드되고 실행도 되겠지만 그게 다이다. 원하는 대로 스크립트 안의 함수나 변수를 사용하려면 스크립트 로딩이 끝났는지 여부를 알 수 있어야 한다.

- loadScript의 두번째 인수로 스크립트 로딩이 끝난 후 실행될 함수인 콜백(callback) 함수를 추가해 보자(콜백함수는 나중에 호출할 함수를 의미한다)
```js
function loadScripty(src, callback) {
  let scirpt = document.createElement('script');
  script.src = src;

  scirpt.onload = () => callback(script);

  document.head.append(script);
}
```

- 새롭게 불러온 스크립트에 있는 함수를 콜백 함수 안에서 호출하면 원하는 대로 외부 스크립트 안의 함수를 사용할 수 있다.

```js
loadScript('/my/script.js', function() {
  // 콜백 함수는 스크립트 로드가 끝나면 실행된다.
newFunctionJ(); // 이제 함수 호출이 제대로 동작한다.
...
});
```

- 이렇게 두번째 인수로 전달된 함수(대개 익명 함수)는 원하는 동작(위 예제에선 외부 스크립트를 불러오는것)이 완료되었을 때 실행된다.

- 아래는 실제 존재하는 스크립트를 이용해 만든 예시이다.
```js
function loadScript(src, callback) {
  let scirpt = document.createElement('script');
  script.src = src;
  script.onload = () => callback(script);
  document.head.append(scirpt);
}

loadScript('https://cdnjs.cloudflare.com/ajax/livs/lodash.js/3.2.0/lodash.js', script => {
  alert(`${scirpt.src}가 로드되었습니다.`);
  alert( _ ); // 스크립트에 정의된 함수
});
```
- 이런 방식을 '콜백 기반(callback-based)' 비동기 프로그래밍이라고 한다. 무언가르 ㄹ비동기적으로 수행하는 함수는 함수내 동작이 모두 처리된 후 실행되어야 하는 함수가 들어갈 콜백을 인수로 반드시 제공해야 한다.
- 위 예시에선 loadScript의 인수로 콜백을 제공해 주었는데 이렇게 콜백을 사용한 방식은 비동기 프로그래밍의 일반적인 접근법이다.



## 콜백 속 콜백

- 스크립트가 두개 잇는 경우 어떻게 하면 두 스크립트를 순차적으로 불러올 수 있을까? 두번재 스크립트 로딩은 첫번재 스크립트의 로딩이 끝난 이후가 되길 원한다면 말이다.
- 가장 자연스로운 해결 방법은 아래와 같이 콜백 함수 안에서 두번재 loadScript를 호출하는 것이다.

```js
loadScript('/my/script.js', function(script) {

  alert(`${scirpt.src}을 로딩했습니다. 이젠 다음 스크립트를 로딩합시다.`);

  loadScript('/my/script2.js', fucntion(script) {
    alert(`두번째 스크립트를 성공적으로 로딩했습니다.`);
  });
});
```
  - 이렇게 중첩 콜백을 만들면 바깥에 위치한 laodScript가 완료된 후 안쪽 loadScript가 실행된다.
  - 그런데 여기에 더하여 스크립트를 하나더 불러오고 싶다면 어떻게 해야할까?
```js
loadscirpt('/my/scirpt.js', function(scirpt) {
  loadscirpt('/my/scirpt2.js', function(scirpt) {
    loadScript('/my/scipt3.js', function(script) {
      // 세 스크립트 로딩이 끝난 후 실행됨
    });
  });
});
```
- 위와 같이 모든 새로운 동작이 콜백 안에 위치하게 작성하면 된다. 그런데 이렇게 콜백 안에 콜백을 넣는 것은 수행하려는 동작이 단 몇개 뿐이라면 괜찮지만 동작이 많은 경우엔 좋지 않다.
- 밑에서 추가 설명 ㄱㄱ

## 에러 핸들링

- 지금까지 살펴본 예시들은 스크립트 로딩이 실패하느 경우 등의 에러를 고려하지 ㅇ낳고 작성되었다. 그런데 스크립트 로딩이 실패할 가능성은 언제나 있다. 물론 콜백함수는 에러를 핸들링 할 수 있어야 한다.
- loadScirpt에서 로딩 에러를 추적할 수 있게 기능을 개선해보자.
```js
function loadScript(src, callback) {
  let scirpt = document.createEelement('script');
  script.src = src;

  scirpt.onload = () => callback(null, script);
  scirpt.onerror = () => callback(new Error(`${src}를 불러오는 도중에 에러가 발생했습니다.);

  document.head.append(scirpt);
}
```
- 이제 loadScript는 스크립트 로딩에 성공하면 callback(null, script)을 실패하면 callback(error)을 호출합니다.
- 개선된 loadScript의 사용법은 다음과 같다.
```js
loadScript('/my/scirpt.js', funcion(error, script) {
  if (error) {
    // 에러 처리
  } else {
      // 스크립트 로딩이 성공적으로 끝남
  }
});
```
- 이렇게 에럴르 처리하는 방식은 흔히 사용되는 패턴이다. 이런 패턴은 '오류 우선 콜백(error-first callback)'이라고 불린다.
- 오류 우선 콜백은 당므 관례를 따른다.
  - 1. callback의 첫번째 인수는 에러를 위해 남겨둔다. 에러가 발생하면 이 인수를 이용해 callback(err)이 호출된다.
  - 2. 두번째 인수(필요하면 인수를 더 추가할 수 있음)는 에러가 발생하지 않았을때를 위해 남겨둔다. 원하는 동작이 성공한 경우엔 callback(null, result1, result2...)이 호출된다.


## 멸망의 피라미드

- 콜백 기반 비동기 처리는 언뜻 봣을 때 꽤 슬만해 보이고 실제로도 그렇다. 한개 혹은 두개의 중첩 호출이 있는 경우는 보기에도 나쁘지 않다.
- 하지만 꼬꼬무 비동기 동작이 많아지면 아래와 같은 코드 작성이 불가피해진다.
```js
loadScript('1.js', function(error, script) {

  if (error) {
    handleError(error);
  } else {
    // ...
    loadScript('2.js', function(error, script) {
      if(error) {
        handleError(error);
      } else {
        // ...
        loadScript('3.js', function(error, script) {
          if (error) {
            handleError(error);
          } else {
            // 모든 스크립트가 로딩된 후 실행 흐름이 이어진다. (*)
          }
         });
        }
      });
      }
    });
  }
}); // 에라이... !@#$%
```
- 위 코드는 다음과 같이 동작한다.
  1. 1.js를 로드합니다. 그 후 에러가 없으면
  2. 2.js를 로드합니다. 그 후 에러가 없으면,
  3. 3.js를 로드합니다. 그 후 에러가 없으면 (*)로 표시한 줄에서 또 다른 작업을 수행한다.
 
- 호출이 계속 중첩되면서 코드가 깊어지고 있다. 본무 중간중간...로 표시한 곳에 반복문과 조건문이 있는 코드가 들어가면 관리는 특히나 더 힘들어 질거다.
- 이렇게 깊은 중첩 코드가 만들어내는 패턴은 소위 `콜백 지옥(callback hell)` 혹은 '멸망의 피라미드(pyramid of doom)' 라고 불린다.

- 비동기 동작이 하나씩 추가될 때마다 중첩 호출이 만들어내는 '피라미드'는 오른쪽으로 점점 커진다. 곧 손쓸 수 없는 지경이 되어버린다.
- 따라서 이런 코딩 방식은 좋지 ㅇ낳다.
- 각 동작을 독립적인 함수로 만들어 위와 같은 문제를 완화해 보도록 하자
```js
loadScript('1.js', stip1();

function step1(error, script) {
  if (error) {
      handleError(error);
  } else {
    // ...
    loadScript('2.js', step2) {
  }
}
function step2(error, script) {
  if (error) {
    handleError(error);
  } else {
    // ...
    loadScript('3.js', step3);
  }
}
function step3(error, script) {
  if (error) {
    handleError(error);
  } else {
    // 모든 스크립트가 로딩되면 다른 동작을 수행한다. (*)
  ]
];
```
- 새롭게 작성한 코드는 각 동작을 분리해 최상위 레벨의 함수로 만들었기 때문에 깊은 중첩이 없다. 그리고 콜백 기반 스타일 코드와 동일하게 동작한다.
- 그런데 이렇게 작성하면 동작상의 문제는 없지만 코드가 찢어진 종잇조각 같아 보인다는 문제가 생긴다. 읽는 것도 어려워지고 눈을 이리저리 움직이며 코드를 읽어야 한다. 코드에 익숙지 않아 눈을 어디로 옮겨야 할지 모르면 더욱더 불편할 것이다.
- 게다가 step* 이라고 명명한 함수들은 '멸망의 피라미드'를 피하려는 용도만으로 만들었기 때문에 재사용이 불가능하다.
- 그 누구도 연쇄 동작이 이뤄지는 코드 밖에선 함수들을 재활용하지 않을 것이다. 네임스페이스가 약간 복잡해졌네요(namespace cluttering).
- 멸망의 피라미드를 피할 방법이 몇가지 있지만 가장 좋은 방법 중 하나는 '프라미스'(promise)'를 사용하는 것이다.


## 프라미스 (promise)

- 1. '제작 코드(producing code)'는 원격에서 스크립트를 불러오는 것 같은 시간이 걸리는 일을 한다.
  2. '소비 코드(consuming code)'는 '제작 코드'의 결과를 기다렸다가 이를 소비한다. 이때 소비 주체(함수)는 여럿이 될 수 있다.
  3. '프라미스(promise)'는 '제작코드'와 '소비 코드'를 연결해 주는 특별한 자바스크립트 객체이다.
 
```js
  let promise = new Promise(function(resolve, reject) {
    // executor(실행자, 실행 함수)
});
```
- new Promise 에 전달되는 함수는 executor(실행자, 실행 함수) 라고 부른다. executor는 new Promise 가 만들어질 때 자동으로 실행되는데 결과적으로 만들어내는 제작 코드를 포함한다.
- executor의 인수 resolve 와 reject 는 자바스크립트에서 자체 제공하는 콜백이다. 개발자는 resolve 와 reject를 신경 쓰지 않고 executor 안 코드만 작성하면 된다.
- 대신 executor에선 겨로가를 즉시 덛든 늦게 얻든 상관없이 상황에 따라 인수로 넘겨준 콜백 중 한를 반드시 호출해야 한다.
  - resolve(value) - 일이 성공적으로 끝난 경우 그 결과를 나타내는 value 와 함께 호출
  - reject(error) - 에러 발생 시 에러 객체를 나타내는 error 와 함께 호출
- 요약하면 executor는 자동으로 실행되는데 여기서 원하느 일이 처리된다. 처리가 끝나면 executor는 처리 성공 여부에 따라 resolve나 reject를 호출한다.
- 한편 new Promise 생성자가 반환하는 promise 객체는 다음과 같은 내부 프로퍼티를 갖는다.
  - state = 처음엔 "ending"(보류)이었다 resolve 가 호출되면 "fulfilled", reject 가 호출되면 "rejected"로 변한다.
  - result = 처음엔 undefined 이었다 resolve(value) 가 호출되면 value 로 reject(error) 가 호출되면 error 로 변한다.
- 따라서 excutor는 아래 그림과 같이 promise의 상태를 둥 중 하나로 변화시킨다.

  ```notepad
                              --->      
                          resolve(value)  state: "fulfilled"
                        /                 result: value
  new Promise(executor)
    state: "pending"
    result: undefined                
                        \     --->
                          reject(error)  state: "rejected"
                                         result: error
  ```

- promise 생성자와 간단한 executor 함수로 만든 예시를 살펴보자. setTimeout을 이용해 executor 함수는 약간의 시간이 걸리도록 구현해봤다.
```js
let promise = new Promise(function(resolve, reject) {
  // 프라미스가 만들어지면 executor 함수는 자동으로 실행된다.

  // 1초 뒤에 일이 성공적으로 끝났다는 신호가 전달되면서 result는 '완료'가 된다.
  setTimeout(() => resolve("완료", 1000);
});
```
- 위 예시를 통해서 우리가 알 수 있는 것은 두가지이다.
  1. executor는 new Promise에 의해 자동으로 그리고 즉각적으로 호출된다.
  2. executor는 인자로 resolve와 reject 함수를 받는다. 이 함수들은 자바스크립트 엔진이 미리 정의한 함수이므로 개발자가 따로 만들 필요가 없다. 다만 resolve 나 reject 중 하나는 반드시 호출해야 한다.
     executor '처리'가 시작된 지 1초 후, resolve("완료") 이 호출되고 결과가 만들어진다. 이 때 promise 객체의 상태는 다음과 같이 변한다.

```notepad
  new Promise(executor)
    state: "pending"       resolve("완료")
    result: undefined          --->          state: "fulfilled"
                                             result: "완료"

- 1초 후 reject(...)가 호출되면 promise의 상태가 "rejected"로 변한다.

 
  new Promise(executor)
    state: "pending"       reject(Error객체)
    result: undefined          --->          state: "rejected"
                                             result: Error객체
```

- 지금까지 배운 내용을 요약해 보자.
- executor는 보통 시간이 걸리는 일을 수행한다. 일이 끝나면 resolve 나 reject 함수를 호출하는데 이때 프라미스 객체의 상태가 변화한다.
- 이행(resolved) 혹은 거부(rejected) 상태의 프라미스는 `처리된(settled)` 프라미스라고 부른다. 반대되는 프라미스로 '대기(pending)'상태의 프라미스가 있다.


### 프라미스는 성공 또는 실패만 한다.

- executor 는 resolve 나 reject 중 하나를 반드시 호출해야 한다. 이 때 변경된 상태는 더 이상 변하지 ㅇ낳는다.
- 처리가 끝난 프라미스에 resolve 와 reject 와 reject 를 호출하면 무시된다.

```js
let promise = new Promise(function(resolve, reject) {
  resolve("완료");

  reject(new Error("...")); // 무시됨
  setTimeout(() => resolve("..."); // 무시됨
});
```
- 이렇게 executor에 의해 처리가 긑난 일은 결과 혹은 에러만 가질 수 있다.
- 여기에 더하여 resolve 나 reject 는 인수를 하나만 받고( 혹은 아무것도 받지 않음) 그 외의 인수는 무시한다는 특성도 있다.

### Error 객체와 함께 거부하기

  - 무언가 잘못된 경우 executor는 reject를 호출해야 한다. 이때 인수는 resolve 와 마찬가지로 어떤 타입도 가능하지만 Error 객체 또는 Error를 상속 받는 객체를 사용할 것을 추천한다.

### resolve.reject 함수 즉시 호출하기

- executor는 대개 무언가를 비동기적으로 수행하고 약간의 시간이 지난 후에 resolve, reject를 호출하는데 꼭 이렇게 할 필요는 없다.
- 아래와 같이 resolve 나 reject를 즉시 호출할 수도 있다.

```js
let promise = new Promise(function(resolve, reject) {
  // 일을 끝마치는 데 시간이 들지 않음
  resovle(123); // 결과(123)를 즉시 resolve에 전달함
});
```
- 어떤 일을 시작했는데 알고 보니 일이 이미 끝나 저장까지 되어있는 겨웅 이렇게 resovle 나 reject를 즉시 호출하는 방식을 사용할 수 있다.
- 이렇게 하면 프라미스는 즉시 이행 상태가 된다.

### state 와 result는 내부에 있다.

- 프라미스 객체의 state, result 프로퍼티는 내부 프로퍼티이므로 개발자가 직접 접근할 수 없다.
- .then .catch .finally 메서드를 사용하면 접근 가능하다.


## then, catch, finally

- 프라미스 객체는 executor와 결과나 에러를 받을 소비 함수를 이어주는 역할을 한다.
- 소비함수는 .then .catch .finally 메서드를 사용해 등록된다.


## then

- .then 은 프라미스에서 가장 주요하고 기본이 되는 메서드이다.

```js
promise.then(
  function(result) {  }, // 결과 (result)를 다룬다.
  function(error) {  }   // 에러 (error)를 다룬다.
);
```
- .then의 첫번째 인수는 프라미스가 이행되었을 때 실행되는 함수이고 여기서 실행 결과를 받는다.
- .then의 두번째 인수는 프라미스가 거부되었을 때 실행되는 함수이고 여기서 에러를 받는다.

- 아래 예시는 성곶거으로 이행된 프라미스에 어떻게 반응하는지 보여준다.

```js
let promise = new Promise(function(resolve, reject) {
  setTimeout(() => resolve("완료!"), 1000)
});

// resove 함수는 .then의 첫번째 함수(인수)를 실행한다.
promise.then(
  result => alert(result), // 1초 후 "완료!"를 출력
  error => alert(error)    // 실행되지 않음
);
```
- 첫번째 함수가 실행되었다.

- 프라미스가 거부된 경우에는 아래와 같이 두번째 함수가 실행된다.
```js
let promise = new Promise(function(resolve, reject) {
  setTimeout(() => reject(new Error("에러 발생!")), 1000);
});

//reject 함수는 .then의 두번째 함수를 실행한다.
promise.then)
  result => alert(result), // 실행되지 않음
  error => alert(error)    // 1초 후 "error: 에러 발생!" 을 출력
```

- 작업이 성공적으로 처리된 경우만 다루고 싶다면 .then에 인수를 하나만 전달하면 된다.
```js
let promise = new Promise(resolve => {
  setTimeout(() => resovle("완료!"), 1000);
});
promise.then(alert); // 1초 뒤 "완료!" 출력
```

## catch

- 에러가 발생한 경우만 다루고 싶다면 .then(null, errorHandlingFunction) 같이 null을 첫번째 인수로 전달하면 된다.
- .catch(errorHandlingFunction)를 써도 되는데 .catch 는 .then 에 null 을 전달하는 것과 동일하게 작동한다.

```js
let promise - new Promise((resolve, reject) => {
  setTimeout(() => reject(new Error("에러 발생!")), 1000);
});

// .catch(f) 는 promise.then(null, f) 과 동일하게 작동한다.
promise.catch(alert); // 1초 뒤 "Error: 에러 발생!" 출력
```

## finally

- try {...} catch {...} 에 finally 절이 있는 것처럼 프라미스에도 finally 가 있다.
- 프라미스가 처리되면(이행이나 거부) f 가 항상 실행된다는 점에서 . finally(f) 호출은 .then(f, f) 과 유사하다.
- 쓸모가 없어진 로디 인디케이터(loading indicator)를 멈추는 경우같이 결과가 어떻든 마무리가 필요하면 finally 가 유용하다.

- 사용법은 아래와 같다.
```js
new Promise((resolve, reject) => {
  // 시간이 걸리느 어떤 일을 수행하고 그 후 resolve, reject를 호출함
})

  // 성공 실패 여부와 상관없이 프라미스가 처리되면 실행됨
  .finally(() => 로딩 인디케이터 중지)
  .then(result => result와 err 보여줌 => error 보여줌)
``

- 그런데 finally 는 .then(f, f) 과 완전히 같지 않다. 차이점은 다음과 같다
  1. finally 핸들러엔 인수가 없다. finally 에선 프라미스가 이행되었는지 거부되었는지 알 수 없다.
     finally 에선 절차를 마무리하는 `보편적` 동작을 수행하기 때문에 성공 실패 여부를 몰라도 된다.

  2. finally 핸들러는 자동으로 다음 핸들러에 결과와 에러를 전달한다.
     result 가 finally 를 거쳐 then 까지 전달되는것을 확인해 보자
  ```js
  new promise((resolve, reject) +. {
    setTimeout(() => resolve("결과"), 2000)
  })
    .finally(() => alert("프라미스가 준비되었습니다."))
    .then(result => alert(result)); // .then에서 result를 다룰 수 있음
  ```
  - 프라미스에서 에러가 발생하고 이 에러가 finally를 거쳐 catch 까지 전달되는 것을 확인해보자.
  ```js
  enw Promise((resolve, reject) => {
    throw new Error("에러 발생!");
  })
    .finally(() => alert("프라미스가 준비되었습니다."))
    .catch(err => alert(err)); // .catch 에서 에러 객체를 다룰 수 있다.
  ```
  - finally는 프라미스 결과를 처리하기 위해 만들어 진 게 아니다. 프라미스 결과는 finally를 통과해서 전달된다.

  3. .finally(f) 는 함수 f를 중복해서 쓸 필요가 없기 때문에 .then(f, f) 보다 문법 측면에서 더 편리하다.


### 처리된 프라미스의 핸들러는 즉각 실행된다.

- 프라미스가 대기 상태일 때 .then catch finally 핸들러는 프라미스가 처리되길 기다린다. 반면 프라미스가 이미 처리상태라면 핸들러가 즉각 실행된다.

```js
// 아래 프라미스는 생성과 동시에 이행된다.
let promise = new Promise(resolve => resolve("완료!"));

promise.then(alert); // 완료! (바로 출력됨)
```

